###############################################################################
# Sobre GitHub Actions                                                        #
# https://docs.github.com/en/actions/learn-github-actions                     #
# https://www.youtube.com/watch?v=TLB5MY9BBa4                                 #
###############################################################################
#
# Atualiza, automaticamente, o arquivo changelog sempre que houver um release
# valendo-se das configurações definidas no branch main.
#

name: Update Changelog

on:
  release:
    types: [released]

jobs:
  update:
    uses: fruivita/.github/.github/workflows/update-changelog.yml@main
